name: oratio_app
description: "An app for booking mass, Making donations and getting closer to God"
publish_to: "none"
version: 0.1.1+8

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  flutter_app_lock: ^4.1.1+1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  local_auth: ^2.3.0
  go_router: ^14.2.1
  dio: ^5.7.0
  confirm_dialog: ^1.0.4
  permission_handler:
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  onesignal_flutter: ^5.2.9
  firebase_core: ^2.25.5
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  filesystem_picker: ^4.0.0
  path_provider: ^2.1.4
  file_picker: ^10.2.0
  flutter_chat_ui: ^1.6.15
  open_filex: ^4.5.0
  lottie: ^3.1.3
  animations: ^2.0.11
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1
  uuid: ^4.5.1
  mime: ^2.0.0
  pocketbase: ^0.18.1
  intl: ^0.19.0
  flutter_paystack_plus: 2.1.0
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  animate_do: ^3.3.4
  glass: ^2.0.0+2
  video_player: ^2.8.1
  pdf: ^3.11.1
  share_plus: ^10.1.3
  app_links: ^6.3.3
  web_socket_channel: ^3.0.1
  cached_network_image: ^3.4.1
  flutter_contacts: ^1.1.9+2
  package_info_plus: ^8.2.0
  screenshot: ^3.0.0
  ace_toast: ^0.0.2
  in_app_update: ^4.2.5
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash:
  flutter_launcher_icons: ^0.14.1
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/wallet_bg.jpeg
    - assets/images/app_logo.png
    - assets/lottie/
    - assets/banks.json
    - assets/images/onboarding/
  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/itim/Itim-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  android_12:
    color: "#ffffff"
    image: assets/images/app_logo.png
  fullscreen: true

  # From Android 12 onwards, the splash screen is handled differently than in previous versions.
  # Please visit https://developer.android.com/guide/topics/ui/splash-screen
  # Following are specific parameters for Android 12+.

  # App icon background color.
  #icon_background_color: "#111111"
  # The branding property allows you to specify an image used as branding in the splash screen.
  #branding: assets/dart.png

  # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  # apply when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #color_dark: "#042a49"
  #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_bottom_padding_android: 24
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_bottom_padding_ios: 24
  #branding_dark_ios: assets/dart_dark-ios.png
  #branding_web: assets/brand-web.gif
  #branding_dark_web: assets/dart_dark-web.gif

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top], );

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

  # dev_dependencies:
  # flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"
